# Generated by cucumber-sinatra. (2013-02-25 20:07:42 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'capybara/poltergeist'
require 'rspec'

Capybara.javascript_driver = :poltergeist

Capybara.app = Sinatra::Application

class CoJaPlaceWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  CoJaPlaceWorld.new
end
